name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Pre-install
        run: |
          yarn
          npx ganache-cli@~6.9.1 > ganache-cli.log &
      - name: Run tests
        run: |
          yarn lint
          yarn build
          yarn coverage
          yarn migrate
          git status