name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Pre-install
        run: |
          yarn install --check-files --cache-folder .ycache
          rm -rf .ycache
          npx ganache-cli@~6.10.2 > ganache-cli.log &
      - name: Run Checks
        run: |
          yarn lint
          yarn prettier
      - name: Run tests
        run: |
          yarn build
          yarn coverage
      - name: Run migration
        run: |
          yarn migrate
      - name: Run check git
        run: |
          git status --porcelain
